name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Setup Deno 🚧
              uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.23.X

            - name: Install and Build 🔧
              run: |
                  deno task build

            - name: Commit files ✅
              run: |
                  git config --local user.email "${{ github.event.pusher.email }}"
                  git config --local user.name "${{ github.event.pusher.name }}"
                  git add -A && git commit -m "Updated extension package"

            - name: Push changes 🔼
              uses: ad-m/github-push-action@master
              with:
                  branch: master
                  github_token: ${{ secrets.GITHUB_TOKEN }}
